### ISSUE TITLE
Daily template has both 24 and 00 hour slots in the time log

### ISSUE THREAD

**Issue by str4d** [philpalmieri/adhd-remarkable-templates#1]
De-duplicating these slots would make the time log shorter; this could be used to extend the "Today's Priority" section by one, but I do kind of like that section being specifically constrained to a small number of entries.

**Comment by philpalmieri** [comment]
thanks, sorry i just saw this, ill take a look this weekend and see if i can update it

**Comment by Dawn1231** [comment]
How do I sideload these templates to my remarkable 2?

**Comment by philpalmieri** [comment]
@Dawn1231 i use https://www.freeremarkabletools.com/
